# Generated by Django 5.2.4 on 2025-07-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculo',
            name='analise_ia',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
