# Generated by Django 5.2.4 on 2025-07-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0002_curriculo_analise_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculo',
            name='email_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
